export const servicesArray = [
  {
    id: 1,
    imgBefore: "/img/services/1-before.jpg",
    imgAfter: "/img/services/1-after.jpg",
    service: "Чистка и обновление обуви из замши",
    price: "60",
    tern: "7",
    promo: "Замшевая обувь - это стильно, но это требует особого ухода",
    stage1: "Глубокая очистка ",
    text1: "избавляем обувь от грязи, пыли и пятен",
    stage2: "Восстановление ворса ",
    text2: "поднимаем ворс, освежаем цвет, возвращаем обуви изначальный лоск",
    stage3: "Защита от влаги ",
    text3: " пропитка водоотталкивающим средством для долговременного эффекта",
    stage4: "",
    text4: "",
    stage5: "",
    text5: "",

    about1: "Используем только лучшие средства и современные технологии",
    about2: "Учитываем особенности каждой пары обуви и ее историю",

    question1: "Можно ли нарастить замшу?",
    answer1:
      "К сожалению, мы не можем нарастить замшу так, чтобы это было незаметно и качественно. Однако, если речь идет о небольших повреждениях, мы можем попытаться их восстановить ",
    question2: "Можно ли удалить масло с замши?",
    answer2:
      "Мы можем удалить масло с замши, но только если пятно свежее, менее суток. Если масло впиталось в материал более суток, удалить его уже сложнее ",
    question3: "Как ухаживать за замшей в домашних условиях?",
    answer3:
      "1. Сушка: После носки наполните обувь бумагой и оставьте сушиться при комнатной температуре.  2. Очистка: При необходимости удалите грязь щеткой для одежды. Если нужно, используйте теплую мыльную воду, но не мочите замшу сильно. 3. Восстановление ворса: Аккуратно расчешите замшу щеткой из латуни. 4. Защита: Обработайте обувь бесцветным водоотталкивающим средством для замши.",
    question4: "Можете ли вы покрасить белую замшевую обувь?",
    answer4:
      "Да, мы можем покрасить вашу белую замшевую обувь! Однако, если обувь сильно изношена и давно используется, то вернуть ей первоначальный цвет будет сложно или не возможно ",
    question5: "",
    answer5: "",
  },
  {
    id: 2,
    imgBefore: "/img/services/2-before.jpg",
    imgAfter: "/img/services/2-after.jpg",
    service: "Чистка и обновление обуви из кожи",
    price: "60",
    tern: "7",

    stage1: "",
    text1: "",
    stage2: "",
    text2: "",
    stage3: "",
    text3: "",
    stage4: "",
    text4: "",
    stage5: "",
    text5: "",

    question1: "",
    answer1: "",
    question2: "",
    answer2: "",
    question3: "",
    answer3: "",
    question4: "",
    answer4: "",
    question5: "",
    answer5: "",
  },
  {
    id: 3,
    imgBefore: "/img/services/3-before.jpg",
    imgAfter: "/img/services/3-after.jpg",
    service: "Выведение реагентов",
    price: "75",
    tern: "7",

    stage1: "",
    text1: "",
    stage2: "",
    text2: "",
    stage3: "",
    text3: "",
    stage4: "",
    text4: "",
    stage5: "",
    text5: "",

    question1: "",
    answer1: "",
    question2: "",
    answer2: "",
    question3: "",
    answer3: "",
    question4: "",
    answer4: "",
    question5: "",
    answer5: "",
  },
  {
    id: 4,
    imgBefore: "/img/services/4-before.jpg",
    imgAfter: "/img/services/4-after.jpg",
    service: "Реставрация, устранение порезов, царапин, трещин",
    price: "110",
    tern: "10",

    stage1: "",
    text1: "",
    stage2: "",
    text2: "",
    stage3: "",
    text3: "",
    stage4: "",
    text4: "",
    stage5: "",
    text5: "",

    question1: "",
    answer1: "",
    question2: "",
    answer2: "",
    question3: "",
    answer3: "",
    question4: "",
    answer4: "",
    question5: "",
    answer5: "",
  },
  {
    id: 5,
    imgBefore: "/img/services/6-before.jpg",
    imgAfter: "/img/services/6-after.jpg",
    service: "Патинирование",
    price: "95",
    tern: "10",

    stage1: "",
    text1: "",
    stage2: "",
    text2: "",
    stage3: "",
    text3: "",
    stage4: "",
    text4: "",
    stage5: "",
    text5: "",

    question1: "",
    answer1: "",
    question2: "",
    answer2: "",
    question3: "",
    answer3: "",
    question4: "",
    answer4: "",
    question5: "",
    answer5: "",
  },
  {
    id: 6,
    imgBefore: "/img/services/6-before.jpg",
    imgAfter: "/img/services/6-after.jpg",
    service: "Восстановление сумок",
    price: "60",
    tern: "10",

    stage1: "",
    text1: "",
    stage2: "",
    text2: "",
    stage3: "",
    text3: "",
    stage4: "",
    text4: "",
    stage5: "",
    text5: "",

    question1: "",
    answer1: "",
    question2: "",
    answer2: "",
    question3: "",
    answer3: "",
    question4: "",
    answer4: "",
    question5: "",
    answer5: "",
  },
];
